### ISSUE TITLE
New SenderID eventhough we are inputing the existing SenderID to createTransaction() method

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Send-API#10]
New SenderID eventhough we are inputing the existing SenderID to createTransaction() method.
Step to reproduce the bug:
1. Do a "select \* from dbo.CUSTOMER_Senders" to mark down the records
2. The call createTransaction(), make sure senderID = 0
3. Take a note of the SenderID in the response
4. Modify the SenderID in the createTransaction() request to the value returned from Step 3, and execute the createTransaction() method

The expected result is the SenderID in the response from Step 4 should be the same as in Step 3. You will note the SenderID in the response is not the same as in Step 3.

**Comment by jctopo** [comment]
I couldn't reproduce this bug. I'm getting the correct SenderID, even when I don't supply SenderID, but supply same sender information.

**Comment by pmt-it** [comment]
Found out the issue is with Test App. Fixed.
