### ISSUE TITLE
GetPayoutLocations() has errors

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Send-API#13]
![image](https://cloud.githubusercontent.com/assets/6502098/5592400/19c82c82-91c5-11e4-8035-abfcdb4908e6.png)

**Comment by jctopo** [comment]
This is not an Send API issue, is an issue in the client, please refer to,

https://social.msdn.microsoft.com/Forums/silverlight/en-US/5cd76441-6452-4114-98e3-5be7b3074404/the-maximum-message-size-quota-for-incoming-messages-65536-has-been-exceeded-to-increase-the?forum=silverlightdevtools

**Comment by pmt-it** [comment]
ok
