### ISSUE TITLE
ModifyTransaction()

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Send-API#14]
See screen attached below. I'm able to modify the transaction with almost not data at all. 

We should set mandatory values before the system update the transaction.
1. Beneficiary FirstName and Lastname must be mandatory
2. Beneficiary CountryCode must be mandatory (rule already exist)
3. If "AD", either AccountNumber or IBAN must be mandatory

![image](https://cloud.githubusercontent.com/assets/6502098/5592417/e1fd92e6-91c5-11e4-8499-f440d4c81981.png)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Verified
