### ISSUE TITLE
Missing fields in Table from CreateTransaction method

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Send-API#2]
select \* from dbo.TRAN_Transaction where PayoutReferenceID in ('PRID123','PRID124','PRID125')

Did couple of test transaction - however the following fields are not saved into the table:
OriginAgentID
OrigenLocationID
SenderIDType
SenderIDIssueDate
SenderIDExpiryDate
SenderIDIssuerCountryCode

Please check. The sample file for the TestHarness can be found at C:\Users\qapmtuser\Desktop\API Test XMLs\CreateTransaction_1.xml

**Comment by jctopo** [comment]
Fixed

![data](https://f.cloud.github.com/assets/6925815/2406604/f58271ea-aa73-11e3-9910-d4d11445fbb1.jpg)
