### ISSUE TITLE
Transactions created not on Admin Panel

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Send-API#3]
Created transaction 'PRID123','PRID124','PRID125' - exist in DB

HINT: Exec select \* from [AGENT_AccountStatementMovs] where AgentID is null

![image](https://f.cloud.github.com/assets/6502098/2388292/43a3f93c-a940-11e3-95dc-2754e6d65181.png)

**Comment by jctopo** [comment]
CreateTransaction method is already saving OriginAgentID, thats why we can see the transaction in admin panel now. But we need to discuss about sending agents in API. Remember we first create this panel for PAK Exchange, a Master Sending agent, but I'm not sure if PMT will function as a master sending again now. The question is , if we treat sending agents as agents or master agents.

![manage](https://f.cloud.github.com/assets/6925815/2406600/e93e69a2-aa73-11e3-86d9-75bec16b5693.jpg)

**Comment by pmt-it** [comment]
OK - Lets discuss this.

**Comment by pmt-it** [comment]
Not an issue anymore
