### ISSUE TITLE
CreateTransaction method's ResponseDate field is empty

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Send-API#4]
See highligted red box

![image](https://f.cloud.github.com/assets/6502098/2404269/8522deba-aa39-11e3-83ef-463ccfc7a3d3.png)

**Comment by jctopo** [comment]
Fixed
![date](https://f.cloud.github.com/assets/6925815/2406560/4d99e8dc-aa73-11e3-8315-9a0211b10fd7.jpg)
