### ISSUE TITLE
Transaction created with Send API cannot be cancelled

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Send-API#5]
Trying to cancel or confirm transaction (PRID134) on Admin Panel

Error when trying to cancel: select \* from dbo.SYSTEM_ErrorLog where ErrorID = 4371
Error when trying to confirm: select \* from dbo.SYSTEM_ErrorLog where ErrorID = 4372

![image](https://f.cloud.github.com/assets/6502098/2408885/f9052d3c-aaa3-11e3-8cd0-32f139cd4d5e.png)

**Comment by jctopo** [comment]
Fixed
