### ISSUE TITLE
Agent Credit Calculation Error

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Send-API#7]
Started with a clean 0.00 balance as you can see below.

![image](https://f.cloud.github.com/assets/6502098/2426553/c540f42a-abc7-11e3-93e1-f0950f6e311b.png)

I'n going to send amount = 100 and fee = 32 from the send api. This agent has 25% commission. So I need to pay PMT 132.

After sending the transaction, I run the two SP scripts:
exec dbo.USP_AGENT_UpdateBalance
exec dbo.USP_AGENT_UpdateMABalance

![image](https://f.cloud.github.com/assets/6502098/2426599/9dd91c36-abc8-11e3-9ff3-57a26a4de732.png)

-Then I CANCEL the transaction on Admin Panel
- After that, I run the two SP scripts:

exec dbo.USP_AGENT_UpdateBalance
exec dbo.USP_AGENT_UpdateMABalance

I got the following:

![image](https://f.cloud.github.com/assets/6502098/2426828/f2bf9d0c-abcc-11e3-9823-cfa3d5465c20.png)

The agent does not need to pay back the commission (8) back to PMT because PMT has NOT pay to the SA the commission yet. 

Note: The agent has paid PMT the face amount plus fee. Total equal 132 (100 +32)

**Comment by jctopo** [comment]
I think what we need to do here is to take out the last row, and put that 8.00 in the row before in the commission column as a negative amount, and at the end of the month, when we do the settlement, we will have +8.00 from the send, and the -8.00 from the cancellation. 

what do you think?

![untitled](https://f.cloud.github.com/assets/6925815/2457250/1fa165d6-af32-11e3-8fb3-ef2966fe40a0.jpg)

**Comment by stevenpoh** [comment]
If I understood you correctly, another way I could explain what you try to tell me is, when you cancel a transaction in the Admin Panel, the system will not try to give back the agent commission if it has NOT been calculated (end of month commission calc). 

Can I ask, if this cancellation from Admin Panel the same cancellation process initiated on the POS SL?

So please deployed and I will try to break it ;)

**Comment by pmt-it** [comment]
Fixed.
