### ISSUE TITLE
Issue with CreateTransaction & ConfirmTransaction

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Send-API#8]
When you create a new transaction via CreateTransaction(), the transaction is in 'PEN' status. The purpose of this is to authorise this transaction on Admin Panel so PMT can act as a gateway to let which transaction to be available for payout.

However, in the Send API, when I, the Send Agent (SA) who uses the API, could actually by pass the Admin Panel step if I execute ConfirmTransaction method. After calling this method, the transaction status becomes 'CON' --> THIS IS A BUG!

So I think we need a new status before 'PEN' if the Send Agent's system require a confirmation step in their system. I remembered you sent me the diagram below a while ago - not sure if this has been implemented. We could use the 'CRE' status as the status before 'PEN'.

So the flow is, if the SA wishes to implement ConfirmTransaction() step, then the typical flow will be:  

CRE (CreateTransaction) -> 'PEN' (ConfirmTransaction) -> 'CON' (Admin Panel)

If the SA does not use ConfirmTransaction() step, then the typical flow will be:
'PEN' (CreateTransaction) -> 'CON' (Admin Panel)

![image-245c05f4bb22d674c07ed85d4f408baaf8fac65a8e52ffa96b6520bca52e7648-v](https://f.cloud.github.com/assets/6502098/2493140/c1aa3aa8-b27d-11e3-8092-70c51b2057cb.jpg)

**Comment by jctopo** [comment]
Fixed
