### ISSUE TITLE
Request fields in the methods

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Send-API#9]
In the send api - getCatalogue(), createTransaction(), ConfirmTxn(), getTxn(), cancelTxn(), getStatement() and getPayoutAgents() has 4 sets of credential fields: MasterAgentID, AgentID, Username and Password.

In getPayoutAgents(), you have CountryCode and ProductCode as input variable to retrieve payout agents per the country code and productcode. This is good, no problem. But in your response, you have AgentID field --> can we rename the field to PayoutAgentID?

In getPayoutLocations(), you have AgentID field but that field is actually the field for payout agent ID. So I propose, we going to have the usual 4 sets of credential fields: MasterAgentID, AgentID, Username and Password. And we have payoutAgentID, currencyCode and productCode field.

**Comment by jctopo** [comment]
Fixed
